package ru.shaldnikita.Tags.web.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TagFormDesign extends VerticalLayout {
    protected TextArea descr;
    protected ComboBox<String> categorySelect;
    protected ComboBox<com.vaadin.ui.Label> markerSelect;
    protected VerticalLayout buttonsLayout;
    protected Button cancel;
    protected Button accept;

    public TagFormDesign() {
        Design.read(this);
    }
}
